name: 'Cinema Mode'
guid: '5fcefe1b-df1f-4596-ac57-f2f939c294c5'
version: '0.6.0.0'
targetAbi: '10.11.0.0'
framework: 'net9.0'
owner: 'CherryFloors'
overview: 'Enable Cinema Mode with local trailers and pre-rolls.'
description: >
  Enable Cinema Mode with local trailers and pre-rolls.
category: 'General'
artifacts:
- 'Jellyfin.Plugin.CinemaMode.dll'
changelog:
  - Target Jellyfin 10.11 ABI and fix broken API.
  - Update "More Like This" trailer selection.
